name = "featherfallorg/quill"
version = "0.1.0"
description = "A lightweight yet extremely powerful game framework."
authors = ["UtterlyTerrible"]
repository = "https://github.com/featherfall-org/quill"
license = "MIT"
includes = [
	"pesde.toml",
	"README.md",
	"LICENSE",
	"src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

